// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_PrandiFabiel_20190281.DAL;

namespace P2_AP1_PrandiFabiel_20190281.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211109004626_Cambiando_ElTipoDeDato_TiempoAcumulado")]
    partial class Cambiando_ElTipoDeDato_TiempoAcumulado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_PrandiFabiel_20190281.Entidades.Proyectos", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("TiempoTotal")
                        .HasColumnType("REAL");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("P2_AP1_PrandiFabiel_20190281.Entidades.ProyectosDetalle", b =>
                {
                    b.Property<int>("ProyectoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("TareaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tiempo")
                        .HasColumnType("REAL");

                    b.HasKey("ProyectoDetalleId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TareaId");

                    b.ToTable("ProyectosDetalle");
                });

            modelBuilder.Entity("P2_AP1_PrandiFabiel_20190281.Entidades.Tareas", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("TiempoAcumulado")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TareaId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            TareaId = 1,
                            TiempoAcumulado = 0.0,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TareaId = 2,
                            TiempoAcumulado = 0.0,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TareaId = 3,
                            TiempoAcumulado = 0.0,
                            TipoTarea = "Programación"
                        },
                        new
                        {
                            TareaId = 4,
                            TiempoAcumulado = 0.0,
                            TipoTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("P2_AP1_PrandiFabiel_20190281.Entidades.ProyectosDetalle", b =>
                {
                    b.HasOne("P2_AP1_PrandiFabiel_20190281.Entidades.Proyectos", null)
                        .WithMany("Detalle")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2_AP1_PrandiFabiel_20190281.Entidades.Tareas", "Tipo")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("P2_AP1_PrandiFabiel_20190281.Entidades.Proyectos", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
