// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_PrandiFabiel_20190281.DAL;

namespace P2_AP1_PrandiFabiel_20190281.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211107225331_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_PrandiFabiel_20190281.Entidades.Tareas", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoAcumulado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TareaId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            TareaId = 1,
                            TiempoAcumulado = 0,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TareaId = 2,
                            TiempoAcumulado = 0,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TareaId = 3,
                            TiempoAcumulado = 0,
                            TipoTarea = "Programación"
                        },
                        new
                        {
                            TareaId = 4,
                            TiempoAcumulado = 0,
                            TipoTarea = "Prueba"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
